apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: apps-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/arulselvan10/gcprepotest
  ref:
    branch: main
