apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app1
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/app1/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: testrepo
  targetNamespace: nginx
